[project]
name = "circle-between-parabolas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "marimo>=0.13.2",
    "seaborn>=0.13.2",
    "sympy>=1.14.0",
]
